/*! \file ipfix_fields.h
*  \brief Hlavi�kov� s�bor obsahuj�ci defin�cie pre k�dovanie a d�ku informa�n�ch elementov IPFIX protokolu
*
*/

#include "ipfix_def.h"


/*
*    This file is part of BEEM.
*
*    BEEM is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    BEEM is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with BEEM.  If not, see <http://www.gnu.org/licenses/>.
*/

ipfix_field_type_t ipfix_field_types[] = {
	{ 0, IPFIX_FT_OCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
	"octetDeltaCount", "" }, 
	{ 0, IPFIX_FT_PACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
	"packetDeltaCount", "" }, 
	{ 0, IPFIX_FT_OBSERVEDFLOWTOTALCOUNTNF, 8, IPFIX_CODING_UINT, 
	"observedFlowTotalCountNF", "" }, 
	{ 0, IPFIX_FT_PROTOCOLIDENTIFIER, 1, IPFIX_CODING_BYTES, 
	"protocolIdentifier", "" }, 
	{ 0, IPFIX_FT_CLASSOFSERVICEIPV4, 1, IPFIX_CODING_BYTES, 
	"classOfServiceIPv4", "" }, 
	{ 0, IPFIX_FT_TCPCONTROLBITS, 1, IPFIX_CODING_BYTES, 
	"tcpControlBits", "" }, 
	{ 0, IPFIX_FT_SOURCETRANSPORTPORT, 2, IPFIX_CODING_UINT, 
	"sourceTransportPort", "" }, 
	{ 0, IPFIX_FT_SOURCEIPV4ADDRESS, 4, IPFIX_CODING_BYTES, 
	"sourceIPv4Address", "" }, 
	{ 0, IPFIX_FT_SOURCEIPV4MASK, 1, IPFIX_CODING_BYTES, 
	"sourceIPv4Mask", "" }, 
	{ 0, IPFIX_FT_INGRESSINTERFACE, 4, IPFIX_CODING_UINT, 
	"ingressInterface", "" }, 
	{ 0, IPFIX_FT_DESTINATIONTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
	"destinationTransportPort", "" }, 
	{ 0, IPFIX_FT_DESTINATIONIPV4ADDRESS, 4, IPFIX_CODING_BYTES, 
	"destinationIPv4Address", "" }, 
	{ 0, IPFIX_FT_DESTINATIONIPV4MASK, 1, IPFIX_CODING_BYTES, 
	"destinationIPv4Mask", "" }, 
	{ 0, IPFIX_FT_EGRESSINTERFACE, 4, IPFIX_CODING_UINT, 
	"egressInterface", "" }, 
	{ 0, IPFIX_FT_IPNEXTHOPIPV4ADDRESS, 4, IPFIX_CODING_BYTES, 
	"ipNextHopIPv4Address", "" }, 
	{ 0, IPFIX_FT_BGPSOURCEASNUMBER, 2, IPFIX_CODING_UINT, 
	"bgpSourceAsNumber", "" }, 
	{ 0, IPFIX_FT_BGPDESTINATIONASNUMBER, 2, IPFIX_CODING_UINT, 
	"bgpDestinationAsNumber", "" }, 
	{ 0, IPFIX_FT_BGPNEXTHOPIPV4ADDRESS, 4, IPFIX_CODING_BYTES, 
	"bgpNextHopIPv4Address", "" }, 
	{ 0, IPFIX_FT_POSTMCASTPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
	"postMCastPacketDeltaCount", "" }, 
	{ 0, IPFIX_FT_POSTMCASTOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
	"postMCastOctetDeltaCount", "" }, 
	{ 0, IPFIX_FT_FLOWENDSYSUPTIME, 4, IPFIX_CODING_UINT, 
	"flowEndSysUpTime", "" }, 
	{ 0, IPFIX_FT_FLOWSTARTSYSUPTIME, 4, IPFIX_CODING_UINT, 
	"flowStartSysUpTime", "" }, 
	{ 0, IPFIX_FT_POSTOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
	"postOctetDeltaCount", "" }, 
	{ 0, IPFIX_FT_POSTPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
	"postPacketDeltaCount", "" }, 
	{ 0, IPFIX_FT_MINIMUMPACKETLENGTH, 2, IPFIX_CODING_UINT, 
	"minimumPacketLength", "" }, 
	{ 0, IPFIX_FT_MAXIMUMPACKETLENGTH, 2, IPFIX_CODING_UINT, 
	"maximumPacketLength", "" }, 
	{ 0, IPFIX_FT_SOURCEIPV6ADDRESS, 16, IPFIX_CODING_BYTES, 
	"sourceIPv6Address", "" }, 
	{ 0, IPFIX_FT_DESTINATIONIPV6ADDRESS, 16, IPFIX_CODING_BYTES, 
	"destinationIPv6Address", "" }, 
	{ 0, IPFIX_FT_SOURCEIPV6MASK, 1, IPFIX_CODING_BYTES, 
	"sourceIPv6Mask", "" }, 
	{ 0, IPFIX_FT_DESTINATIONIPV6MASK, 1, IPFIX_CODING_BYTES, 
	"destinationIPv6Mask", "" }, 
	{ 0, IPFIX_FT_FLOWLABELIPV6, 4, IPFIX_CODING_UINT, 
	"flowLabelIPv6", "" }, 
	{ 0, IPFIX_FT_ICMPTYPECODEIPV4, 2, IPFIX_CODING_UINT, 
	"icmpTypeCodeIPv4", "" }, 
	{ 0, IPFIX_FT_IGMPTYPE, 1, IPFIX_CODING_BYTES, 
	"igmpType", "" }, 
	{ 0, IPFIX_FT_FLOWACTIVETIMEOUT, 2, IPFIX_CODING_UINT, 
	"flowActiveTimeOut", "" }, 
	{ 0, IPFIX_FT_FLOWINACTIVETIMEOUT, 2, IPFIX_CODING_UINT, 
	"flowInactiveTimeout", "" }, 
	{ 0, IPFIX_FT_EXPORTEDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"exportedOctetTotalCount", "" }, 
	{ 0, IPFIX_FT_EXPORTEDMESSAGETOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"exportedMessageTotalCount", "" }, 
	{ 0, IPFIX_FT_EXPORTEDFLOWTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"exportedFlowTotalCount", "" }, 
	{ 0, IPFIX_FT_SOURCEIPV4PREFIX, 4, IPFIX_CODING_BYTES, 
	"sourceIPv4Prefix", "" }, 
	{ 0, IPFIX_FT_DESTINATIONIPV4PREFIX, 4, IPFIX_CODING_BYTES, 
	"destinationIPv4Prefix", "" }, 
	{ 0, IPFIX_FT_MPLSTOPLABELTYPE, 1, IPFIX_CODING_BYTES, 
	"mplsTopLabelType", "" }, 
	{ 0, IPFIX_FT_MPLSTOPLABELIPV4ADDRESS, 4, IPFIX_CODING_BYTES, 
	"mplsTopLabelIPv4Address", "" }, 
	{ 0, IPFIX_FT_MINIMUMTTL, 1, IPFIX_CODING_BYTES, 
	"minimumTtl", "" }, 
	{ 0, IPFIX_FT_MAXIMUMTTL, 1, IPFIX_CODING_BYTES, 
	"maximumTtl", "" }, 
	{ 0, IPFIX_FT_IDENTIFICATIONIPV4, 4, IPFIX_CODING_UINT, 
	"identificationIPv4", "" }, 
	{ 0, IPFIX_FT_POSTCLASSOFSERVICEIPV4, 1, IPFIX_CODING_BYTES, 
	"postClassOfServiceIPv4", "" }, 
	{ 0, IPFIX_FT_SOURCEMACADDRESS, 6, IPFIX_CODING_BYTES, 
	"sourceMacAddress", "" }, 
	{ 0, IPFIX_FT_POSTDESTINATIONMACADDR, 6, IPFIX_CODING_BYTES, 
	"postDestinationMacAddr", "" }, 
	{ 0, IPFIX_FT_VLANID, 2, IPFIX_CODING_UINT, 
	"vlanId", "" }, 
	{ 0, IPFIX_FT_POSTVLANID, 2, IPFIX_CODING_UINT, 
	"postVlanId", "" }, 
	{ 0, IPFIX_FT_IPVERSION, 1, IPFIX_CODING_BYTES, 
	"ipVersion", "" },
	{ 0, IPFIX_FT_FLOWDIRECTION, 1, IPFIX_CODING_BYTES, 
	"flowDirection", "" }, 
	{ 0, IPFIX_FT_IPNEXTHOPIPV6ADDRESS, 16, IPFIX_CODING_BYTES, 
	"ipNextHopIPv6Address", "" }, 
	{ 0, IPFIX_FT_BGPNEXTHOPIPV6ADDRESS, 16, IPFIX_CODING_BYTES, 
	"bgpNextHopIPv6Address", "" }, 
	{ 0, IPFIX_FT_IPV6EXTENSIONHEADERS, 4, IPFIX_CODING_UINT, 
	"ipv6ExtensionHeaders", "" }, 
	{ 0, IPFIX_FT_MPLSTOPLABELSTACKENTRY, 4, IPFIX_CODING_UINT, 
	"mplsTopLabelStackEntry", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY2, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry2", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY3, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry3", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY4, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry4", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY5, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry5", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY6, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry6", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY7, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry7", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY8, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry8", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY9, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry9", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKENTRY10, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackEntry10", "" }, 
	{ 0, IPFIX_FT_DESTINATIONMACADDRESS, 6, IPFIX_CODING_BYTES, 
	"destinationMacAddress", "" }, 
	{ 0, IPFIX_FT_POSTSOURCEMACADDRESS, 6, IPFIX_CODING_BYTES, 
	"postSourceMacAddress", "" }, 
	{ 0, IPFIX_FT_OCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"octetTotalCount", "" }, 
	{ 0, IPFIX_FT_PACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"packetTotalCount", "" }, 
	{ 0, IPFIX_FT_FRAGMENTOFFSETIPV4, 2, IPFIX_CODING_UINT, 
	"fragmentOffsetIPv4", "" },
	{ 0, IPFIX_FT_MPLSVPNROUTEDISTINGUISHER, 4, IPFIX_CODING_UINT, 
	"mplsVpnRoutedDistinguisher", "" }, 
	{ 0, IPFIX_FT_BGPNEXTADJACENTASNUMBER, 2, IPFIX_CODING_UINT, 
	"bgpNextAdjacentAsNumber", "" }, 
	{ 0, IPFIX_FT_BGPPREVADJACENTASNUMBER, 2, IPFIX_CODING_UINT, 
	"bgpPrevAdjacentAsNumber", "" }, 
	{ 0, IPFIX_FT_EXPORTERIPV4ADDRESS, 4, IPFIX_CODING_BYTES, 
	"exporterIPv4Address", "" }, 
	{ 0, IPFIX_FT_EXPORTERIPV6ADDRESS, 16, IPFIX_CODING_BYTES, 
	"exporterIPv6Address", "" }, 
	{ 0, IPFIX_FT_DROPPEDOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
	"droppedOctetDeltaCount", "" }, 
	{ 0, IPFIX_FT_DROPPEDPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
	"droppedPacketDeltaCount", "" }, 
	{ 0, IPFIX_FT_DROPPEDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"droppedOctetTotalCount", "" }, 
	{ 0, IPFIX_FT_DROPPEDPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"droppedPacketTotalCount", "" }, 
	{ 0, IPFIX_FT_FLOWENDREASON, 1, IPFIX_CODING_BYTES, 
	"flowEndReason", "" }, 
	/*
	{ 0, IPFIX_FT_CLASSOFSERVICEIPV6, 1, IPFIX_CODING_BYTES, 
	"classOfServiceIPv6", "" }, 
	{ 0, IPFIX_FT_POSTCLASSOFSERVICEIPV6, 1, IPFIX_CODING_BYTES, 
	"postClassOfServiceIPv6", "" }, 
	*/
	{ 0, IPFIX_FT_COMMONPROPERTIESID, 8, IPFIX_CODING_UINT,
	"commonPropertiesId", "" },
	{ 0, IPFIX_FT_OBSERVATIONPOINTID, 4, IPFIX_CODING_UINT,
	"observationPoindId", "" },
	{ 0, IPFIX_FT_ICMPTYPECODEIPV6, 2, IPFIX_CODING_UINT, 
	"icmpTypeCodeIPv6", "" }, 
	{ 0, IPFIX_FT_MPLSTOPLABELIPV6ADDRESS, 16, IPFIX_CODING_BYTES, 
	"mplsTopLabelIPv6Address", "" }, 
	{ 0, IPFIX_FT_LINECARDID, 4, IPFIX_CODING_UINT, 
	"lineCardId", "" }, 
	{ 0, IPFIX_FT_PORTID, 4, IPFIX_CODING_UINT, 
	"portId", "" }, 
	{ 0, IPFIX_FT_METERINGPROCESSID, 4, IPFIX_CODING_UINT, 
	"meteringProcessId", "" }, 
	{ 0, IPFIX_FT_EXPORTINGPROCESSID, 4, IPFIX_CODING_UINT, 
	"exportingProcessId", "" }, 
	{ 0, IPFIX_FT_TEMPLATEID, 2, IPFIX_CODING_UINT, 
	"templateId", "" }, 
	{ 0, IPFIX_FT_WLANCHANNELID, 1, IPFIX_CODING_BYTES, 
	"wlanChannelId", "" }, 
	{ 0, IPFIX_FT_WLANSSID, 65535, IPFIX_CODING_STRING, 
	"wlanSsid", "" }, 
	{ 0, IPFIX_FT_FLOWID, 8, IPFIX_CODING_UINT, 
	"flowId", "" }, 
	{ 0, IPFIX_FT_OBSERVATIONDOMAINID, 4, IPFIX_CODING_UINT, 
	"observationDomainId", "" }, 
	{ 0, IPFIX_FT_FLOWSTARTSECONDS, 4, IPFIX_CODING_UINT, 
	"flowStartSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWENDSECONDS, 4, IPFIX_CODING_UINT, 
	"flowEndSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWSTARTMILLISECONDS, 8, IPFIX_CODING_UINT, 
	"flowStartMilliSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWENDMILLISECONDS, 8, IPFIX_CODING_UINT, 
	"flowEndMilliSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWSTARTMICROSECONDS, 8, IPFIX_CODING_UINT, 
	"flowStartMicroSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWENDMICROSECONDS, 8, IPFIX_CODING_UINT, 
	"flowEndMicroSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWSTARTNANOSECONDS, 8, IPFIX_CODING_UINT, 
	"flowStartNanoSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWENDNANOSECONDS, 8, IPFIX_CODING_UINT, 
	"flowEndNanoSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWSTARTDELTAMICROSECONDS, 4, IPFIX_CODING_UINT, 
	"flowStartDeltaMicroSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWENDDELTAMICROSECONDS, 4, IPFIX_CODING_UINT, 
	"flowEndDeltaMicroSeconds", "" }, 
	{ 0, IPFIX_FT_SYSTEMINITTIMEMILLISECONDS, 8, IPFIX_CODING_UINT, 
	"systemInitTimeMilliSeconds", "" }, 
	{ 0, IPFIX_FT_FLOWDURATIONMILLISECONDS, 4, IPFIX_CODING_UINT, 
	//biju sa IPNEXTHOPASNUMBER 162 s FLOWDURATIONMICROSECONDS 162 tiez..
//	"flowDurationMilliSeconds", "" }, 
//	{ 0, IPFIX_FT_IPNEXTHOPASNUMBER, 2, IPFIX_CODING_UINT, 
	"ipNextHopAsNumber", "" }, 
	{ 0, IPFIX_FT_FLOWDURATIONMICROSECONDS, 4, IPFIX_CODING_UINT, 
	"flowDurationMicroSeconds", "" }, 
	{ 0, IPFIX_FT_OBSERVEDFLOWTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"observedFlowTotalCount", "" }, 
	{ 0, IPFIX_FT_IGNOREDPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"ignoredPacketTotalCount", "" }, 
	{ 0, IPFIX_FT_IGNOREDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"ignoredOctetTotalCount", "" }, 
	{ 0, IPFIX_FT_NOTSENTFLOWTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"notSentFlowTotalCount", "" }, 
	{ 0, IPFIX_FT_NOTSENTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"notSentPacketTotalCount", "" }, 
	{ 0, IPFIX_FT_NOTSENTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"notSentOctetTotalCount", "" }, 
	{ 0, IPFIX_FT_DESTINATIONIPV6PREFIX, 16, IPFIX_CODING_BYTES, 
	"destinationIPv6Prefix", "" }, 
	{ 0, IPFIX_FT_SOURCEIPV6PREFIX, 16, IPFIX_CODING_BYTES, 
	"sourceIPv6Prefix", "" }, 
	{ 0, IPFIX_FT_POSTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"postOctetTotalCount", "" }, 
	{ 0, IPFIX_FT_POSTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"postPacketTotalCount", "" }, 
	{ 0, IPFIX_FT_FLOWKEYINDICATOR, 8, IPFIX_CODING_UINT, 
	"flowKeyIndicator", "" }, 
	{ 0, IPFIX_FT_POSTMCASTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"postMCastPacketTotalCount", "" }, 
	{ 0, IPFIX_FT_POSTMCASTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
	"postMCastOctetTotalCount", "" }, 
	{ 0, IPFIX_FT_ICMPTYPEIPV4, 1, IPFIX_CODING_BYTES, 
	"icmpTypeIPv4", "" }, 
	{ 0, IPFIX_FT_ICMPCODEIPV4, 1, IPFIX_CODING_BYTES, 
	"icmpCodeIPv4", "" }, 
	{ 0, IPFIX_FT_ICMPTYPEIPV6, 1, IPFIX_CODING_BYTES, 
	"icmpTypeIPv6", "" }, 
	{ 0, IPFIX_FT_ICMPCODEIPV6, 1, IPFIX_CODING_BYTES, 
	"icmpCodeIPv6", "" }, 
	{ 0, IPFIX_FT_UDPSOURCEPORT, 2, IPFIX_CODING_UINT, 
	"udpSourcePort", "" }, 
	{ 0, IPFIX_FT_UDPDESTINATIONPORT, 2, IPFIX_CODING_UINT, 
	"udpDestinationPort", "" }, 
	{ 0, IPFIX_FT_TCPSOURCEPORT, 2, IPFIX_CODING_UINT, 
	"tcpSourcePort", "" }, 
	{ 0, IPFIX_FT_TCPDESTINATIONPORT, 2, IPFIX_CODING_UINT, 
	"tcpDestinationPort", "" }, 
	{ 0, IPFIX_FT_TCPSEQUENCENUMBER, 4, IPFIX_CODING_UINT, 
	"tcpSequenceNumber", "" }, 
	{ 0, IPFIX_FT_TCPACKNOWLEDGEMENTNUMBER, 4, IPFIX_CODING_UINT, 
	"tcpAcknowledgementNumber", "" }, 
	{ 0, IPFIX_FT_TCPWINDOWSIZE, 2, IPFIX_CODING_UINT, 
	"tcpWindowSize", "" }, 
	{ 0, IPFIX_FT_TCPURGENTPOINTER, 2, IPFIX_CODING_UINT, 
	"tcpUrgentPointer", "" }, 
	{ 0, IPFIX_FT_TCPHEADERLENGTH, 2, IPFIX_CODING_UINT, 
	"tcpHeaderLength", "" }, 
	{ 0, IPFIX_FT_IPHEADERLENGTH, 1, IPFIX_CODING_BYTES, 
	"ipHeaderLength", "" }, 
	{ 0, IPFIX_FT_TOTALLENGTHIPV4, 2, IPFIX_CODING_UINT, 
	"totalLengthIPv4", "" }, 
	{ 0, IPFIX_FT_PAYLOADLENGTHIPV6, 4, IPFIX_CODING_UINT, 
	"payloadLengthIPv6", "" },
	{ 0, IPFIX_FT_IPPAYLOADLENGTH, 4, IPFIX_CODING_UINT, 
	"ipPayloadLength", "" }, 
	{ 0, IPFIX_FT_IPTIMETOLIVE, 1, IPFIX_CODING_BYTES, 
	"ipTimeToLive", "" }, 
	{ 0, IPFIX_FT_NEXTHEADERIPV6, 1, IPFIX_CODING_BYTES, 
	"nextHeaderIPv6", "" }, 
	{ 0, IPFIX_FT_IPCLASSOFSERVICE, 1, IPFIX_CODING_BYTES, 
	"ipClassOfService", "" }, 
	{ 0, IPFIX_FT_IPDIFFSERVCODEPOINT, 1, IPFIX_CODING_BYTES, 
	"ipDiffServCodePoint", "" }, 
	{ 0, IPFIX_FT_IPPRECEDENCE, 1, IPFIX_CODING_BYTES, 
	"ipPrecedence", "" }, 
	{ 0, IPFIX_FT_FRAGMENTFLAGSIPV4, 1, IPFIX_CODING_BYTES, 
	"fragmentFlagsIPv4", "" }, 
	{ 0, IPFIX_FT_OCTETDELTASUMOFSQUARES, 8, IPFIX_CODING_UINT, 
	"octetDeltaSumOfSquares", "" }, 
	{ 0, IPFIX_FT_OCTETTOTALSUMOFSQUARES, 8, IPFIX_CODING_UINT, 
	"octetTotalSumOfSquares", "" }, 
	{ 0, IPFIX_FT_MPLSTOPLABELTTL, 4, IPFIX_CODING_UINT, 
	"mplsTopLabelTtl", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKLENGTH, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackLength", "" }, 
	{ 0, IPFIX_FT_MPLSLABELSTACKDEPTH, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackDepth", "" }, 
	{ 0, IPFIX_FT_MPLSTOPLABELEXP, 1, IPFIX_CODING_BYTES, 
	"mplsTopLabelExp", "" }, 
	{ 0, IPFIX_FT_IPPAYLOADLENGTH, 8, IPFIX_CODING_UINT, 
	"ipPayloadLength", "" }, 
	{ 0, IPFIX_FT_UDPMESSAGELENGTH, 2, IPFIX_CODING_UINT, 
	"udpMessageLength", "" }, 
	{ 0, IPFIX_FT_ISMULTICAST, 1, IPFIX_CODING_BYTES, 
	"isMulticast", "" }, 
	{ 0, IPFIX_FT_INTERNETHEADERLENGTHIPV4, 1, IPFIX_CODING_BYTES, 
	"internetHeaderLengthIPv4", "" }, 
	{ 0, IPFIX_FT_IPV4OPTIONS, 4, IPFIX_CODING_UINT, 
	"ipv4Options", "" }, 
	{ 0, IPFIX_FT_TCPOPTIONS, 8, IPFIX_CODING_UINT, 
	"tcpOptions", "" }, 
	{ 0, IPFIX_FT_PADDINGOCTETS, 1, IPFIX_CODING_BYTES, 
	"paddingOctets", "" }, 
	{ 0, IPFIX_FT_EXPORTINTERFACE, 1, IPFIX_CODING_BYTES, 
	"exportInterface", "" }, 
	{ 0, IPFIX_FT_EXPORTPROTOCOLVERSION, 1, IPFIX_CODING_UINT, 
	"exportProtocolVersion", "" },
	{ 0, IPFIX_FT_EXPORTTRANSPORTPROTOCOL, 1, IPFIX_CODING_UINT, 
	"exportTransportProtocol", "" },
	{ 0, IPFIX_FT_COLLECTORTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
	"collectorTransportPort", "" },
	{ 0, IPFIX_FT_EXPORTERTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
	"exporterTransportPort", "" },

	{ 0, IPFIX_FT_TCPSYNTOTALCOUNT, 8, IPFIX_CODING_UINT,
	"tcpSynTotalCount", "" },
	{ 0, IPFIX_FT_TCPFINTOTALCOUNT, 8, IPFIX_CODING_UINT,
	"tcpFinTotalCount", "" },
	{ 0, IPFIX_FT_TCPRSTTOTALCOUNT, 8, IPFIX_CODING_UINT,
	"tcpRstTotalCount", "" },
	{ 0, IPFIX_FT_TCPPSHTOTALCOUNT, 8, IPFIX_CODING_UINT,
	"tcpPshTotalCount", "" },
	{ 0, IPFIX_FT_TCPACKTOTALCOUNT, 8, IPFIX_CODING_UINT,
	"tcpAckTotalCount", "" },
	{ 0, IPFIX_FT_TCPURGTOTALCOUNT, 8, IPFIX_CODING_UINT,
	"tcpUrgTotalCount", "" },
	{ 0, IPFIX_FT_IPTOTALLENGTH, 8, IPFIX_CODING_UINT,
	"ipTotalLength", "" },
	{ 0, IPFIX_FT_NATORIGINSIDEADDR, 4, IPFIX_CODING_BYTES, 
	"natOrigInsideAddr", "" },
	{ 0, IPFIX_FT_NATTRANSINSIDEADDR, 4, IPFIX_CODING_BYTES, 
	"natTransInsideAddr", "" },
	{ 0, IPFIX_FT_NATORIGOUTSIDEADDR, 4, IPFIX_CODING_BYTES, 
	"natOrigOutsideAddr", "" },
	{ 0, IPFIX_FT_NATTRANSOUTSIDEADDR, 4, IPFIX_CODING_BYTES, 
	"natTransOutsideAddr", "" },

	{ 0, IPFIX_FT_NATORIGINSIDEPORT, 2, IPFIX_CODING_UINT, 
	"natOrigInsidePort", "" },
	{ 0, IPFIX_FT_NATTRANSINSIDEPORT, 2, IPFIX_CODING_UINT, 
	"natTransInsidePort", "" },
	{ 0, IPFIX_FT_NATORIGOUTSIDEPORT, 2, IPFIX_CODING_UINT, 
	"natOrigOutsidePort", "" },
	{ 0, IPFIX_FT_NATTRANSOUTSIDEPORT, 2, IPFIX_CODING_UINT, 
	"natTransOutsidePort", "" },

	{ 0, IPFIX_FT_NATEVENT, 2, IPFIX_CODING_UINT, 
	"natEvent", "" },
	{ 0, IPFIX_FT_FWINITIATOROCTETS, 4, IPFIX_CODING_UINT, 
	"fwInitiatorOctets", "" },
	{ 0, IPFIX_FT_FWRESPONDEROCTETS, 4, IPFIX_CODING_UINT, 
	"fwResponderOctets", "" },
	{ 0, IPFIX_FT_FWEVENT, 1, IPFIX_CODING_UINT, 
	"fwEvent", "" },
	{ 0, IPFIX_FT_POSTMPLSTOPLABELEXP, 1, IPFIX_CODING_UINT, 
	"postMplsTopLabelExp", "" },
	{ 0, IPFIX_FT_TCPWINDOWSCALE, 2, IPFIX_CODING_UINT, 
	"tcpWindowScale", "" },
	{ 0, IPFIX_FT_OBSERVATIONPROCESSID, 8, IPFIX_CODING_UINT, 
	"observationPointId", "" },
	{ 0, IPFIX_FT_SELECTIONSEQUENCEID, 8, IPFIX_CODING_UINT, 
	"selectionSequenceId", "" },

	{ 0, IPFIX_FT_SELECTORID, 2, IPFIX_CODING_UINT, 
	"selectorId", "" },
	{ 0, IPFIX_FT_INFORMATIONELEMENTID, 2, IPFIX_CODING_UINT, 
	"informationElementId", "" },
	{ 0, IPFIX_FT_SELECTORALGORITHM, 2, IPFIX_CODING_UINT, 
	"selectorAlgorithm", "" },
	{ 0, IPFIX_FT_SAMPLINGPACKETINTERVAL, 4, IPFIX_CODING_UINT, 
	"samplingPacketInterval", "" },

	{ 0, IPFIX_FT_SAMPLINGPACKETSPACE, 4, IPFIX_CODING_UINT, 
	"samplingPacketSpace", "" },
	{ 0, IPFIX_FT_SAMPLINGTIMEINTERVAL, 8, IPFIX_CODING_UINT, 
	"samplingTimeInterval", "" },
	{ 0, IPFIX_FT_SAMPLINGTIMESPACE, 8, IPFIX_CODING_UINT, 
	"samplingTimeSpace", "" },
	{ 0, IPFIX_FT_SAMPLINGSIZE, 4, IPFIX_CODING_UINT, 
	"samplingSize", "" },

	{ 0, IPFIX_FT_SAMPLINGPOPULATION, 4, IPFIX_CODING_UINT, 
	"samplingPopulation", "" },
	{ 0, IPFIX_FT_SAMPLINGPROBABILITY, 8, IPFIX_CODING_FLOAT, 
	"samplingProbability", "" },
	{ 0, IPFIX_FT_DATALINKFRAMESIZE, 4, IPFIX_CODING_UINT, 
	"dataLinkFrameSize", "" },
//TODO doriesit typy pri najblizsich piatich elementoch - octetarray
	{ 0, IPFIX_FT_IPHEADERPACKETSECTION, 20, IPFIX_CODING_BYTES, 
	"ipHeaderPacketSection", "" },
	{ 0, IPFIX_FT_IPPAYLOADPACKETSECTION, 20, IPFIX_CODING_BYTES, 
	"ipPayloadPacketSection", "" },
	{ 0, IPFIX_FT_DATALINKFRAMESECTION, 4, IPFIX_CODING_UINT, 
	"dataLinkFrameSection", "" },
	{ 0, IPFIX_FT_MPLSLABELSTACKSECTION, 4, IPFIX_CODING_UINT, 
	"mplsLabelStackSection", "" },
	{ 0, IPFIX_FT_MPLSPAYLOADPACKETSECTION, 4, IPFIX_CODING_UINT, 
	"mplsPayloadPacketSection", "" },

	{ 0, IPFIX_FT_PACKETSOBSERVED, 8, IPFIX_CODING_UINT, 
	"packetsObserved", "" },
	{ 0, IPFIX_FT_PACKETSSELECTED, 8, IPFIX_CODING_UINT, 
	"dataLinkFrameSection", "" },
	{ 0, IPFIX_FT_FIXEDERROR, 8, IPFIX_CODING_FLOAT, 
	"fixedError", "" },
	{ 0, IPFIX_FT_RELATIVEERROR, 8, IPFIX_CODING_FLOAT, 
	"relativeError", "" },

	{ 0, IPFIX_FT_OBSERVATIONTIMESECONDS, 4, IPFIX_CODING_UINT, 
	"observationTimeSeconds", "" },
	{ 0, IPFIX_FT_OBSERVATIONTIMEMILISECONDS, 8, IPFIX_CODING_UINT, 
	"observationTimeMilliseconds", "" },
	{ 0, IPFIX_FT_OBSERVATIONTIMEMICROSECONDS, 8, IPFIX_CODING_UINT, 
	"observationTimeMicroseconds", "" },
	{ 0, IPFIX_FT_OBSERVATIONTIMENANOSECONDS, 8, IPFIX_CODING_UINT, 
	"observationTimeNanoseconds", "" },
	{ 0, IPFIX_FT_DIGESTHASHVALUE, 8, IPFIX_CODING_UINT, 
	"digestHashValue", "" },
	{ 0, IPFIX_FT_HASHIPPAYLOADOFFSET, 8, IPFIX_CODING_UINT, 
	"hashIPPayloadOffset", "" },
	{ 0, IPFIX_FT_HASHIPPAYLOADSIZE, 8, IPFIX_CODING_UINT, 
	"hashIPPayloadSize", "" },
	{ 0, IPFIX_FT_HASHINITIALISERVALUE, 8, IPFIX_CODING_UINT, 
	"hashInitialiserValue", "" },
	{ 0, IPFIX_FT_HASHOUTPUTRANGEMIN, 8, IPFIX_CODING_UINT, 
	"hashOutputRangeMin", "" },
	{ 0, IPFIX_FT_HASHOUTPUTRANGEMAX, 8, IPFIX_CODING_UINT, 
	"hashOutputRangeMax", "" },
	{ 0, IPFIX_FT_HASHSELECTEDRANGEMIN, 8, IPFIX_CODING_UINT, 
	"hashSelectedRangeMin", "" },
	{ 0, IPFIX_FT_HASHSELECTEDRANGEMAX, 8, IPFIX_CODING_UINT, 
	"hashSelectedRangeMax", "" },
	{ 0, IPFIX_FT_HASHDIGESTOUTPUT, 1, IPFIX_CODING_BOOL, 
	"hashDigestOutput", "" },
	{ 0, IPFIX_FT_ORIGINALFLOWSPRESENT, 8, IPFIX_CODING_UINT, 
	"originalFlowsPresent", "" },
	{ 0, IPFIX_FT_ORIGINALFLOWSINITIATED, 8, IPFIX_CODING_UINT, 
	"originalFlowsInitiated", "" },
	{ 0, IPFIX_FT_ORIGINALFLOWSCOMPLETED, 8, IPFIX_CODING_UINT, 
	"originalFlowsCompleted", "" },
	{ 0, IPFIX_FT_DISTINCTCOUNTOFSOURCEIPADDRESS, 8, IPFIX_CODING_UINT, 
	"distinctCountOfSourceIPAddress", "" },
	{ 0, IPFIX_FT_DISTINCTCOUNTOFDESTINATIONIPADDRESS, 8, IPFIX_CODING_UINT, 
	"distinctCountOfDestinationIPAddress", "" },
	{ 0, IPFIX_FT_DISTINCTCOUNTOFSOURCEIPV4ADDRESS, 4, IPFIX_CODING_UINT, 
	"distinctCountOfSourceIPv4Address", "" },
	{ 0, IPFIX_FT_DISTINCTCOUNTOFDESTINATIONIPV4ADDRESS, 4, IPFIX_CODING_UINT, 
	"distinctCountOfDestinationIPv4Address", "" },
	{ 0, IPFIX_FT_DISTINCTCOUNTOFSOURCEIPV6ADDRESS, 8, IPFIX_CODING_UINT, 
	"distinctCountOfSourceIPv6Address", "" },
	{ 0, IPFIX_FT_DISTINCTCOUNTOFDESTINATIONIPV6ADDRESS, 8, IPFIX_CODING_UINT, 
	"distinctCountOfDestinationIPv6Address", "" },

        //***************************************************************
        { 0, IPFIX_FT_COLLECTORIPV4ADDRESS, 4, IPFIX_CODING_UINT, 
	"collectorIPv4Address", "" },
        { 0, IPFIX_FT_COLLECTORIPV6ADDRESS, 16, IPFIX_CODING_UINT, 
	"collectorIPv6Address", "" },
	{0, IPFIX_FT_APPLICATIONID, 4, IPFIX_CODING_BYTES,
	"applicationId", "" },
	{0, IPFIX_FT_APPLICATIONNAME, 32, IPFIX_CODING_BYTES,
	"applicationName", "" },
        //***************************************************************

	{26235, IPFIX_FT_ROUNDTRIPTIMENANOSECONDS, 8, IPFIX_CODING_UINT,
	"roundTripTimeNanoseconds", "" },
	{26235, IPFIX_FT_RTTPAIRSTOTALCOUNT, 8, IPFIX_CODING_UINT,
	"rttPairsTotalCount", "" },
	{26235, IPFIX_FT_FIRSTPACKETID, 16, IPFIX_CODING_BYTES,
	"firstPacketID", "" },
	{26235, IPFIX_FT_LASTPACKETID, 16, IPFIX_CODING_BYTES,
	"lastPacketID", "" },
	{26235, IPFIX_FT_FLOWSTARTAFTEREXPORT, 8, IPFIX_CODING_UINT,
	"flowStartAfterExport", "" },
        
        //********************NF5_PADDINGS******************************
	{0, NF5_FT_PADDING1, 1, IPFIX_CODING_UINT,
	"8BitPadding", "" },
	{0, NF5_FT_PADDING2, 2, IPFIX_CODING_UINT,
	"16BitPadding", "" },
       
	{ 0, 0, -1, 0, "", "" }
};
